#数据源配置 jdbc
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ticketsellingsystem?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.ironman.ticketsellingsystem.entity
  type-handlers-package: org.ironman.ticketsellingsystem.dao
# 其他配置暂时注释掉
#    configuration:
#      cacheEnabled: true
#      lazyLoadingEnabled: true
#      aggressiveLazyLoading: false
#      multipleResultSetsEnabled: true
#      useColumnLabel: true
#      useGeneratedKeys: false
#      autoMappingBehavior: PARTIAL
#      defaultExecutorType: SIMPLE
#      defaultStatementTimeout: 25000
#      safeRowBoundsEnabled: false
#      mapUnderscoreToCamelCase: false
#      localCacheScope: SESSION
#      jdbcTypeForNull: OTHER
#      lazyLoadTriggerMethods: equals,clone,hashCode,toString
#      callSettersOnNulls: true
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
